In [1]:
import numpy as np

Multiple Indexing

    m[[ax1_i],[ax2_i]...]


In [4]:
a1 = np.array([1,2,3,4,5])
a1[[1,2,3]]

array([2, 3, 4])

In [12]:
a2 = np.array([[1,2,3], [13, 14, 15]])
a2[[1], [1,2]]

array([14, 15])

In [25]:
a3 = np.array([[[1,2, 10], [3,4,20]], [[5,6, 30], [7,8, 40]]])
a3[[0], [0, 1], [2]]

array([10, 20])

In [6]:
a4 = np.array([1,2,3])
a4[a4<=2] = 10
a4

array([10, 10,  3])

In [5]:
n1 = np.array([1,5,20,9,8,19,3])
n12 = np.array([11,51,201,91,81,191,31])
si1 = np.argsort(n1)
di1 = si1[::-1]
n2 = n12[di1[:3]]
n2

array([201, 191,  91])